import { Link } from "wouter";
import { useListBlogs, useListTechniques, getListBlogsQueryKey } from "@workspace/api-client-react";
import { Database, Filter, Layers, Code2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { VariantCard } from "@/components/variant-card";
import { Skeleton } from "@/components/ui/skeleton";

export function BlogIndex() {
  const { data: blogList, isLoading: blogsLoading } = useListBlogs({ query: { queryKey: getListBlogsQueryKey() } });
  const { data: techniquesList, isLoading: techLoading } = useListTechniques();

  return (
    <div className="flex-1 flex flex-col md:flex-row w-full min-h-[calc(100vh-3.5rem)]">
      {/* Sidebar Filter */}
      <aside className="w-full md:w-64 lg:w-72 border-r border-border/40 bg-card/30 p-6 shrink-0 md:sticky md:top-14 h-auto md:h-[calc(100vh-3.5rem)] overflow-y-auto">
        <div className="flex items-center gap-2 font-mono font-bold text-lg mb-6 tracking-tight text-primary">
          <Filter className="w-4 h-4" />
          <span>TECHNIQUES</span>
        </div>
        
        {techLoading ? (
          <div className="space-y-3">
            {[1,2,3,4,5,6].map(i => <Skeleton key={i} className="h-8 w-full rounded-none" />)}
          </div>
        ) : (
          <nav className="flex flex-col space-y-1">
            {techniquesList?.techniques.map(tech => (
              <Link key={tech.slug} href={`/blog/${tech.slug}`}>
                <div className="px-3 py-2 text-sm font-mono text-muted-foreground hover:bg-primary/10 hover:text-primary transition-colors cursor-pointer border-l-2 border-transparent hover:border-primary group flex items-center justify-between">
                  <span className="truncate">{tech.label}</span>
                </div>
              </Link>
            ))}
          </nav>
        )}
      </aside>

      {/* Main Content */}
      <div className="flex-1 p-6 lg:p-10 xl:p-14 overflow-y-auto bg-background/50">
        <div className="max-w-5xl mx-auto space-y-16">
          <div className="space-y-4">
            <h1 className="text-4xl font-bold tracking-tight">Technical Variants Blog</h1>
            <p className="text-xl text-muted-foreground max-w-2xl leading-relaxed">
              Explore diverse algorithmic solutions categorized by technique. A living library generated by the Studio engine.
            </p>
            {!blogsLoading && blogList && (
              <div className="flex items-center gap-2 pt-4 font-mono text-sm">
                <Badge variant="outline" className="rounded-none bg-primary/10 text-primary border-primary/20">
                  {blogList.totalVariants} TOTAL VARIANTS
                </Badge>
              </div>
            )}
          </div>

          {blogsLoading ? (
            <div className="space-y-12">
              {[1, 2].map(group => (
                <div key={group} className="space-y-6">
                  <Skeleton className="h-8 w-48 rounded-none" />
                  <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-6">
                    {[1,2,3].map(card => <Skeleton key={card} className="h-64 w-full rounded-none" />)}
                  </div>
                </div>
              ))}
            </div>
          ) : !blogList?.groups?.length ? (
            <div className="flex flex-col items-center justify-center p-20 border border-dashed border-border/50 text-center">
              <Database className="w-12 h-12 text-muted-foreground/30 mb-4" />
              <h3 className="text-lg font-mono font-bold mb-2">DATABASE_EMPTY</h3>
              <p className="text-muted-foreground max-w-sm mb-6">No variants have been generated yet. Use the Studio to analyze code and generate variants.</p>
              <Link href="/">
                <div className="px-4 py-2 bg-primary text-primary-foreground font-mono text-sm hover:bg-primary/90 transition-colors inline-flex items-center gap-2 cursor-pointer">
                  <Code2 className="w-4 h-4" /> STUDIO
                </div>
              </Link>
            </div>
          ) : (
            <div className="space-y-20">
              {blogList.groups.map(group => (
                <section key={group.technique} className="space-y-6 relative">
                  <div className="flex items-end justify-between border-b border-border/40 pb-4 sticky top-14 bg-background/95 backdrop-blur z-10 pt-4">
                    <div className="flex items-center gap-3">
                      <Layers className="w-5 h-5 text-primary" />
                      <h2 className="text-2xl font-bold tracking-tight">
                        <Link href={`/blog/${group.technique}`} className="hover:text-primary transition-colors">
                          {group.techniqueLabel}
                        </Link>
                      </h2>
                    </div>
                    <Badge variant="secondary" className="rounded-none font-mono text-xs">
                      {group.variants.length} VARIANTS
                    </Badge>
                  </div>
                  
                  {group.variants.length > 0 ? (
                    <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-6">
                      {group.variants.map(variant => (
                        <VariantCard key={variant.id} variant={variant} />
                      ))}
                    </div>
                  ) : (
                    <div className="p-8 border border-dashed border-border/40 text-center text-muted-foreground font-mono text-sm">
                      NO_VARIANTS_IN_CATEGORY
                    </div>
                  )}
                </section>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
